version: '3.4'

services:
  transactionqueryaggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - TransactionQueryServiceEndpointCsv=http://6e41f821b785.ngrok.io/
      - username=example
      - password=example123456789
    ports:
      - "39433:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
